version: "3.7"

services:
    redis:
        image: redis
        expose:
            - "6379"
        command: redis-server --appendonly yes
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        links:
            - redis
